version: "3.7"
services:
  app:
    build:
      args:
        user: aasumitro
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: oksetdaabsensi
    container_name: oksetdaabsensi-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - oksetdaabsensi

  mariadb:
    image: mariadb:latest
    container_name: oksetdaabsensi-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mariadb
    volumes:
      - ./docker-compose/mariadb:/docker-entrypoint-initdb.d
    networks:
      - oksetdaabsensi

  redis:
    image: redis:alpine
    container_name: oksetdaabsensi-redis
    restart: unless-stopped
    volumes:
      - ./docker-compose/redis:/docker-entrypoint-initdb.d
    networks:
      - oksetdaabsensi

  nginx:
    image: nginx:alpine
    container_name: oksetdaabsensi-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - oksetdaabsensi

networks:
  oksetdaabsensi:
    driver: bridge
